export const CLUB_LOGOS: Record<string, string> = {
  "Atlanta United": "https://media.api-sports.io/football/teams/1608.png",
  "Austin FC": "https://media.api-sports.io/football/teams/16489.png",
  "CF Montreal": "https://media.api-sports.io/football/teams/1614.png",
  "Charlotte FC": "https://media.api-sports.io/football/teams/18310.png",
  "Chicago Fire FC": "https://media.api-sports.io/football/teams/1607.png",
  "Colorado Rapids": "https://media.api-sports.io/football/teams/1610.png",
  "Columbus Crew": "https://media.api-sports.io/football/teams/1613.png",
  "DC United": "https://media.api-sports.io/football/teams/1615.png",
  "FC Cincinnati": "https://media.api-sports.io/football/teams/2242.png",
  "FC Dallas": "https://media.api-sports.io/football/teams/1597.png",
  "Houston Dynamo FC": "https://media.api-sports.io/football/teams/1600.png",
  "Inter Miami CF": "https://media.api-sports.io/football/teams/9568.png",
  "LA Galaxy": "https://media.api-sports.io/football/teams/1605.png",
  "Los Angeles FC": "https://media.api-sports.io/football/teams/1616.png",
  "Minnesota United": "https://media.api-sports.io/football/teams/1612.png",
  "Nashville SC": "https://media.api-sports.io/football/teams/9569.png",
  "New England Revolution": "https://media.api-sports.io/football/teams/1609.png",
  "New York City FC": "https://media.api-sports.io/football/teams/1604.png",
  "Orlando City": "https://media.api-sports.io/football/teams/1598.png",
  "Philadelphia Union": "https://media.api-sports.io/football/teams/1599.png",
  "Portland Timbers": "https://media.api-sports.io/football/teams/1617.png",
  "Real Salt Lake": "https://media.api-sports.io/football/teams/1606.png",
  "Red Bull New York": "https://media.api-sports.io/football/teams/1602.png",
  "San Diego FC": "https://a.espncdn.com/i/teamlogos/soccer/500/22529.png",
  "San Jose Earthquakes": "https://media.api-sports.io/football/teams/1596.png",
  "Seattle Sounders FC": "https://media.api-sports.io/football/teams/1595.png",
  "Sporting Kansas City": "https://media.api-sports.io/football/teams/1611.png",
  "St. Louis City": "https://media.api-sports.io/football/teams/20787.png",
  "Toronto FC": "https://media.api-sports.io/football/teams/1601.png",
  "Vancouver Whitecaps": "https://media.api-sports.io/football/teams/1603.png",
  "AC Milan": "https://cdn.soccerwiki.org/images/logos/clubs/115.png",
  "Angers": "https://cdn.soccerwiki.org/images/logos/clubs/310.png",
  "Arsenal": "https://cdn.soccerwiki.org/images/logos/clubs/1.png",
  "Aston Villa": "https://cdn.soccerwiki.org/images/logos/clubs/2.png",
  "Atalanta": "https://cdn.soccerwiki.org/images/logos/clubs/96.png",
  "Atletic Club": "https://cdn.soccerwiki.org/images/logos/clubs/138.png",
  "Atletico Madrid": "https://cdn.soccerwiki.org/images/logos/clubs/139.png",
  "Augsburg": "https://cdn.soccerwiki.org/images/logos/clubs/750.png",
  "Auxerre": "https://cdn.soccerwiki.org/images/logos/clubs/311.png",
  "Barcelona": "https://cdn.soccerwiki.org/images/logos/clubs/140.png",
  "Bayer Leverkusen": "https://cdn.soccerwiki.org/images/logos/clubs/390.png",
  "Bayern Munich": "https://cdn.soccerwiki.org/images/logos/clubs/391.png",
  "Bologna": "https://cdn.soccerwiki.org/images/logos/clubs/98.png",
  "Borussia Dortmund": "https://cdn.soccerwiki.org/images/logos/clubs/392.png",
  "Borussia M.Gladbach": "https://cdn.soccerwiki.org/images/logos/clubs/393.png",
  "Bournemouth": "https://cdn.soccerwiki.org/images/logos/clubs/9.png",
  "Brentford": "https://cdn.soccerwiki.org/images/logos/clubs/11.png",
  "Brest": "https://cdn.soccerwiki.org/images/logos/clubs/314.png",
  "Brighton": "https://cdn.soccerwiki.org/images/logos/clubs/12.png",
  "Burnley": "https://cdn.soccerwiki.org/images/logos/clubs/15.png",
  "Cagliari": "https://cdn.soccerwiki.org/images/logos/clubs/100.png",
  "Celta Vigo": "https://cdn.soccerwiki.org/images/logos/clubs/141.png",
  "Chelsea": "https://cdn.soccerwiki.org/images/logos/clubs/21.png",
  "Como": "https://cdn.soccerwiki.org/images/logos/clubs/1671.png",
  "Cremonese": "https://cdn.soccerwiki.org/images/logos/clubs/479.png",
  "Crystal Palace": "https://cdn.soccerwiki.org/images/logos/clubs/27.png",
  "Deportivo Alaves": "https://cdn.soccerwiki.org/images/logos/clubs/135.png",
  "Eintracht Frankfurt": "https://cdn.soccerwiki.org/images/logos/clubs/395.png",
  "Elche": "https://cdn.soccerwiki.org/images/logos/clubs/147.png",
  "Espanyol": "https://cdn.soccerwiki.org/images/logos/clubs/148.png",
  "Everton": "https://cdn.soccerwiki.org/images/logos/clubs/31.png",
  "FC Heidenheim": "https://cdn.soccerwiki.org/images/logos/clubs/1513.png",
  "FC Koln": "https://cdn.soccerwiki.org/images/logos/clubs/385.png",
  "Fiorentina": "https://cdn.soccerwiki.org/images/logos/clubs/107.png",
  "Freiburg": "https://cdn.soccerwiki.org/images/logos/clubs/411.png",
  "Fulham": "https://cdn.soccerwiki.org/images/logos/clubs/32.png",
  "Genoa": "https://cdn.soccerwiki.org/images/logos/clubs/108.png",
  "Getafe": "https://cdn.soccerwiki.org/images/logos/clubs/149.png",
  "Girona": "https://cdn.soccerwiki.org/images/logos/clubs/1313.png",
  "Hamburger SV": "https://cdn.soccerwiki.org/images/logos/clubs/401.png",
  "Hoffenheim": "https://cdn.soccerwiki.org/images/logos/clubs/793.png",
  "Inter": "https://cdn.soccerwiki.org/images/logos/clubs/109.png",
  "Juventus": "https://cdn.soccerwiki.org/images/logos/clubs/110.png",
  "Lazio": "https://cdn.soccerwiki.org/images/logos/clubs/111.png",
  "Le Havre": "https://cdn.soccerwiki.org/images/logos/clubs/325.png",
  "Lecce": "https://cdn.soccerwiki.org/images/logos/clubs/112.png",
  "Leeds": "https://cdn.soccerwiki.org/images/logos/clubs/40.png",
  "Lens": "https://cdn.soccerwiki.org/images/logos/clubs/327.png",
  "Levante": "https://cdn.soccerwiki.org/images/logos/clubs/151.png",
  "Lille": "https://cdn.soccerwiki.org/images/logos/clubs/432.png",
  "Liverpool": "https://cdn.soccerwiki.org/images/logos/clubs/44.png",
  "Lorient": "https://cdn.soccerwiki.org/images/logos/clubs/328.png",
  "Lyon": "https://cdn.soccerwiki.org/images/logos/clubs/329.png",
  "Mainz 05": "https://cdn.soccerwiki.org/images/logos/clubs/399.png",
  "Mallorca": "https://cdn.soccerwiki.org/images/logos/clubs/153.png",
  "Man City": "https://cdn.soccerwiki.org/images/logos/clubs/47.png",
  "Man Utd": "https://cdn.soccerwiki.org/images/logos/clubs/49.png",
  "Marseille": "https://cdn.soccerwiki.org/images/logos/clubs/330.png",
  "Metz": "https://cdn.soccerwiki.org/images/logos/clubs/331.png",
  "Monaco": "https://cdn.soccerwiki.org/images/logos/clubs/332.png",
  "Nantes": "https://cdn.soccerwiki.org/images/logos/clubs/335.png",
  "Napoli": "https://cdn.soccerwiki.org/images/logos/clubs/746.png",
  "Newcastle": "https://cdn.soccerwiki.org/images/logos/clubs/52.png",
  "Nice": "https://cdn.soccerwiki.org/images/logos/clubs/336.png",
  "Nottingham Forest": "https://cdn.soccerwiki.org/images/logos/clubs/55.png",
  "Osasuna": "https://cdn.soccerwiki.org/images/logos/clubs/157.png",
  "PSG": "https://cdn.soccerwiki.org/images/logos/clubs/338.png",
  "Paris FC": "https://cdn.soccerwiki.org/images/logos/clubs/1692.png",
  "Parma Calcio": "https://cdn.soccerwiki.org/images/logos/clubs/118.png",
  "Pisa": "https://cdn.soccerwiki.org/images/logos/clubs/872.png",
  "RB Leipzig": "https://cdn.soccerwiki.org/images/logos/clubs/1657.png",
  "Rayo Vallecano": "https://cdn.soccerwiki.org/images/logos/clubs/1298.png",
  "Real Betis": "https://cdn.soccerwiki.org/images/logos/clubs/162.png",
  "Real Madrid": "https://cdn.soccerwiki.org/images/logos/clubs/163.png",
  "Real Oviedo": "https://cdn.soccerwiki.org/images/logos/clubs/1612.png",
  "Real Sociedad": "https://cdn.soccerwiki.org/images/logos/clubs/165.png",
  "Rennes": "https://cdn.soccerwiki.org/images/logos/clubs/340.png",
  "Roma": "https://cdn.soccerwiki.org/images/logos/clubs/123.png",
  "Sassuolo": "https://cdn.soccerwiki.org/images/logos/clubs/862.png",
  "Sevilla": "https://cdn.soccerwiki.org/images/logos/clubs/168.png",
  "St. Pauli": "https://cdn.soccerwiki.org/images/logos/clubs/1109.png",
  "Strasbourg": "https://cdn.soccerwiki.org/images/logos/clubs/344.png",
  "Sunderland": "https://cdn.soccerwiki.org/images/logos/clubs/76.png",
  "Torino": "https://cdn.soccerwiki.org/images/logos/clubs/128.png",
  "Tottenham": "https://cdn.soccerwiki.org/images/logos/clubs/80.png",
  "Toulouse": "https://cdn.soccerwiki.org/images/logos/clubs/345.png",
  "Udinese": "https://cdn.soccerwiki.org/images/logos/clubs/131.png",
  "Union Berlin": "https://cdn.soccerwiki.org/images/logos/clubs/792.png",
  "Valencia": "https://cdn.soccerwiki.org/images/logos/clubs/172.png",
  "Verona": "https://cdn.soccerwiki.org/images/logos/clubs/133.png",
  "VfB Stuttgart": "https://cdn.soccerwiki.org/images/logos/clubs/417.png",
  "Villarreal": "https://cdn.soccerwiki.org/images/logos/clubs/174.png",
  "Werder Bremen": "https://cdn.soccerwiki.org/images/logos/clubs/414.png",
  "West Ham": "https://cdn.soccerwiki.org/images/logos/clubs/85.png",
  "Wolfsburg": "https://cdn.soccerwiki.org/images/logos/clubs/419.png",
  "Wolves": "https://cdn.soccerwiki.org/images/logos/clubs/88.png",
};
