"use client";

import { useMemo, useState } from "react";

import { PlayerAvatar } from "./PlayerAvatar";
import { SeasonDeltaChip } from "./season/SeasonDeltaChip";
import { metricByKey, type PlayerBaseline } from "./season/baselineTypes";

type MetricRow = {
  player?: string;
  minutes_played?: number;
  is_substitute?: boolean;
  touches?: number;
  passes_attempted?: number;
  passes_completed?: number;
  pass_accuracy?: number;
  passes_received?: number;
  avg_pass_distance?: number;
  progressive_passes?: number;
  progressive_passes_received?: number;
  final_third_passes?: number;
  box_passes?: number;
  key_passes?: number;
  xA?: number;
  xT?: number;
  epv_added?: number;
  carries?: number;
  progressive_carries?: number;
  take_ons_won?: number;
  turnovers?: number;
};

type Column = {
  key: keyof MetricRow;
  label: string;
  description: string;
  format?: (value: unknown) => string;
};

type Props = {
  rows: MetricRow[];
  team: string;
  playerBaselines?: Record<string, PlayerBaseline>;
};

// table column -> season-baseline metric key (every stat column is baselined)
const BASELINE_KEYS: Partial<Record<keyof MetricRow, string>> = {
  touches: "touches",
  passes_completed: "passes_completed",
  passes_attempted: "passes_attempted",
  pass_accuracy: "pass_accuracy",
  passes_received: "passes_received",
  avg_pass_distance: "avg_pass_distance",
  progressive_passes: "progressive_passes",
  progressive_passes_received: "progressive_passes_received",
  final_third_passes: "final_third_passes",
  box_passes: "box_passes",
  key_passes: "key_passes",
  xA: "xa",
  xT: "xt",
  epv_added: "epv_added",
  carries: "carries",
  progressive_carries: "prog_carries",
  take_ons_won: "take_ons_won",
  turnovers: "turnovers",
};

const columns: Column[] = [
  { key: "player", label: "Player", description: "Player name." },
  { key: "minutes_played", label: "Min", description: "Estimated minutes played in the match from starting status and substitution events." },
  { key: "touches", label: "Touches", description: "Touches by the player in the selected team across the match." },
  { key: "passes_completed", label: "Cmp", description: "Successful passes completed by the player." },
  { key: "passes_attempted", label: "Att", description: "Total passes attempted by the player." },
  { key: "pass_accuracy", label: "Pass %", description: "Completed passes divided by attempted passes.", format: (value) => `${Number(value ?? 0).toFixed(1)}%` },
  { key: "passes_received", label: "Received", description: "Successful passes received by the player." },
  { key: "avg_pass_distance", label: "Avg Dist", description: "Average distance in meters of the player's successful passes.", format: (value) => `${Number(value ?? 0).toFixed(1)}m` },
  { key: "progressive_passes", label: "Prog Pass", description: "Successful passes that move the ball closer to goal by 30m in own half, 15m across halves, or 10m in the opponent half." },
  { key: "progressive_passes_received", label: "Prog Rec", description: "Successful progressive passes received by the player." },
  { key: "final_third_passes", label: "Final 3rd", description: "Successful passes ending in the final third." },
  { key: "box_passes", label: "Box Pass", description: "Successful passes ending inside the penalty box." },
  { key: "key_passes", label: "Key Pass", description: "Passes identified as shot assists or key chance-creating passes." },
  { key: "xA", label: "xA", description: "Expected assists generated from the player's passes.", format: (value) => Number(value ?? 0).toFixed(3) },
  { key: "xT", label: "xT", description: "Expected threat generated by the player's passes and carries.", format: (value) => Number(value ?? 0).toFixed(3) },
  { key: "epv_added", label: "EPV", description: "Expected possession value added by the player's successful passes and carries.", format: (value) => Number(value ?? 0).toFixed(3) },
  { key: "carries", label: "Carries", description: "Ball carries by the player." },
  { key: "progressive_carries", label: "Prog Carry", description: "Carries that move the ball closer to goal by 30m in own half, 15m across halves, or 10m in the opponent half." },
  { key: "take_ons_won", label: "Take Ons", description: "Successful take-ons completed by the player." },
  { key: "turnovers", label: "TO", description: "Turnovers and dispossessions by the player." },
];

function numeric(value: unknown) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : 0;
}

export function InPossessionMetricsTable({ rows, team, playerBaselines }: Props) {
  const [sortKey, setSortKey] = useState<keyof MetricRow>("passes_attempted");
  const [sortDirection, setSortDirection] = useState<"asc" | "desc">("desc");
  const [showSeasonDeltas, setShowSeasonDeltas] = useState(false);
  const hasBaselines = Boolean(playerBaselines && Object.values(playerBaselines).some((b) => !b.lowSample));

  const sortedRows = useMemo(() => {
    return [...rows].sort((first, second) => {
      if (sortKey === "player") {
        const result = String(first.player ?? "").localeCompare(String(second.player ?? ""));
        return sortDirection === "asc" ? result : -result;
      }
      const result = numeric(first[sortKey]) - numeric(second[sortKey]);
      return sortDirection === "asc" ? result : -result;
    });
  }, [rows, sortDirection, sortKey]);

  const changeSort = (key: keyof MetricRow) => {
    if (key === sortKey) {
      setSortDirection((current) => current === "asc" ? "desc" : "asc");
      return;
    }
    setSortKey(key);
    setSortDirection(key === "player" ? "asc" : "desc");
  };

  return (
    <section className="card stack">
      <div className="chart-card-head">
        <div>
          <span className="eyebrow">Player Metrics</span>
          <h2 style={{ margin: "6px 0 0" }}>In Possession Table - {team}</h2>
        </div>
        {hasBaselines ? (
          <button
            type="button"
            className={showSeasonDeltas ? "button" : "ghost-button"}
            onClick={() => setShowSeasonDeltas((current) => !current)}
          >
            vs season
          </button>
        ) : null}
      </div>
      <div className="in-possession-table-wrap">
        <table className="in-possession-table">
          <thead>
            <tr>
              {columns.map((column) => (
                <th key={column.key}>
                  <button
                    type="button"
                    className="metric-tooltip"
                    data-tooltip={column.description}
                    title={column.description}
                    onClick={() => changeSort(column.key)}
                  >
                    <span>{column.label}</span>
                    {sortKey === column.key && <span>{sortDirection === "asc" ? "↑" : "↓"}</span>}
                  </button>
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {sortedRows.map((row) => (
              <tr key={row.player} className={row.is_substitute ? "is-substitute-row" : ""}>
                {columns.map((column) => (
                  <td key={column.key} className={column.key === "player" ? "is-player" : ""}>
                    {column.key === "player" ? (
                      <span className="player-cell">
                        <PlayerAvatar name={String(row.player ?? "")} team={team} size={24} />
                        <span>{String(row.player ?? "")}</span>
                        {row.is_substitute && <span className="substitute-badge">Sub</span>}
                      </span>
                    ) : (
                      <>
                        {column.format ? column.format(row[column.key]) : String(row[column.key] ?? 0)}
                        {(() => {
                          if (!showSeasonDeltas) return null;
                          const baselineKey = BASELINE_KEYS[column.key];
                          const baseline = playerBaselines?.[String(row.player ?? "")];
                          if (!baselineKey || !baseline || baseline.lowSample) return null;
                          return <SeasonDeltaChip metric={metricByKey(baseline, baselineKey)} per90 />;
                        })()}
                      </>
                    )}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {hasBaselines && showSeasonDeltas ? (
        <p className="chart-footnote">Chips compare each player&apos;s per-90 rate in this match against their season per-90 (excluding this match); hidden for players with under 450 season minutes or under 20 minutes today.</p>
      ) : null}
    </section>
  );
}
